### ISSUE TITLE
Node module crash

### ISSUE THREAD

**Issue by vocksel** [vocksel/roblox-theme-converter#2]
Got a report of this error when attempting to use the `rbxtheme` command. Looks to be caused by a conflict with using Node's module system and `commander` not supporting it. Might be the NodeJS version? I run 14.17.3 which does not have this issue.

```
❯ rbxtheme list           
file:///home/______/.npm-packages/lib/node_modules/rbxtheme/bin/rbxtheme.js:2
import { program } from 'commander'
         ^^^^^^^
SyntaxError: The requested module 'commander' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'commander';
const { program } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

NodeJS v14.9.0

**Comment by vocksel** [comment]
This seems to be related to the node version. When I downgrade to 14.9.0 I can repro the crash. Not sure if there's any way around this since this package uses the new module system.

In any case, 14.15.1 at the least works with this package, so I don't think I'll dedicate time to a fix for older versions
